version: '3.8'

services:
  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-net

  spark-worker-1:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - "./data:/home/jovyan/work"
    networks:
      - spark-net
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2

networks:
  spark-net:
    driver: bridge
